# Generated by Django 4.1.4 on 2024-09-23 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_payment_order_id_alter_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
